from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    version = models.IntegerField(default=1)
    # Extend user model if needed
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    last_login_ip = models.GenericIPAddressField(null=True, blank=True)
    failed_login_attempts = models.IntegerField(default=0)
    is_locked = models.BooleanField(default=False)
    last_activity = models.DateTimeField(null=True, blank=True)
    total_logins = models.IntegerField(default=0)
    profile_completeness = models.FloatField(default=0.0)
    preferred_language = models.CharField(max_length=50, null=True, blank=True)
    documents_generated = models.PositiveIntegerField(default=0, help_text="Total number of documents generated by the user.")
    logic_rules_created = models.PositiveIntegerField(default=0, help_text="Total number of logic rules created by the user.")
    last_document_generated = models.ForeignKey(
        'documents.DocumentTemplate',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='last_generated_by',
        help_text="Reference to the most recently generated document by the user."
    )
    last_logic_rule_created = models.ForeignKey(
        'logic_builder.LogicRule',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='last_created_by',
        help_text="Reference to the most recently created logic rule by the user."
    )
